### ISSUE TITLE
Which license is used in this repo?

### ISSUE THREAD

**Issue by yuehaowang** [759434091/danmu-crawler#1]
Hi, I am excited to see this repo on github since I have spent too much time on searching for danmu crawler. Thanks to this awesome repo, it is just what I am looking for! Now I want to reuse some of the code from this repo in my project but I don't know whether there are some restrictions when reusing your code.
I'd like to know about the license so that I can avoid violation of any rules.

Anyway, thanks again!

**Comment by 759434091** [comment]
MIT .
