### ISSUE TITLE
虎牙抓包疑问

### ISSUE THREAD

**Issue by yjqiang** [759434091/danmu-crawler#2]
虎牙的弹幕有4个url这是为什么呢？
还有虎牙似乎对数据有特殊处理，是加密还是故意混淆了呢？好像虎牙弹幕相关信息很少，我搜了一圈都没怎么找到。
我个人是写python的，对nodejs这一块儿不太熟悉。

**Comment by 759434091** [comment]
> 虎牙的弹幕有4个url这是为什么呢？
> 还有虎牙似乎对数据有特殊处理，是加密还是故意混淆了呢？好像虎牙弹幕相关信息很少，我搜了一圈都没怎么找到。
> 我个人是写python的，对nodejs这一块儿不太熟悉。

是因为有四条线路。 没有混淆， RPC 序列化编码

**Comment by yjqiang** [comment]
我看了协议核心`taf`了，虎牙这协议吃屎一样的复杂。
